name: Build & Deploy Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode dari repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Sesuaikan versi Flutter

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 4️⃣ Build APK
      - name: Build Release APK
        run: flutter build apk --release

      # 5️⃣ Upload APK sebagai artifact (Opsional, untuk diunduh dari GitHub)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    if: success() # Hanya berjalan jika build sukses

    steps:
      # 1️⃣ Checkout kode lagi
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Download APK dari job sebelumnya
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/

      # 3️⃣ Deploy ke Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
